markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-GOOGLES-1

repository: https://github.io/jekyll/jekyll
help_url: https://roachhd.github.io/jekyll/jekyll-help

collections:
  docs:
    output: true

url: roachhd.github.io/jekyll/
baseurl: /jekyll/
